"""empty message

Revision ID: 3564796c9f97
Revises: 455cef4aa513
Create Date: 2023-04-12 20:59:24.966771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3564796c9f97'
down_revision = '455cef4aa513'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialogues', sa.Column('temperature', sa.Float(), nullable=False))
    op.add_column('dialogues', sa.Column('top_p', sa.Float(), nullable=False))
    op.add_column('dialogues', sa.Column('n', sa.Integer(), nullable=False))
    op.add_column('dialogues', sa.Column('max_tokens', sa.Integer(), nullable=False))
    op.add_column('dialogues', sa.Column('presence_penalty', sa.Float(), nullable=False))
    op.add_column('dialogues', sa.Column('frequency_penalty', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dialogues', 'frequency_penalty')
    op.drop_column('dialogues', 'presence_penalty')
    op.drop_column('dialogues', 'max_tokens')
    op.drop_column('dialogues', 'n')
    op.drop_column('dialogues', 'top_p')
    op.drop_column('dialogues', 'temperature')
    # ### end Alembic commands ###
