"""add parse_mode to Dialogue

Revision ID: 97a01d19d4cb
Revises: 4b850abf0d16
Create Date: 2023-05-05 15:37:24.662809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97a01d19d4cb'
down_revision = '4b850abf0d16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialogues', sa.Column('parse_mode', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dialogues', 'parse_mode')
    # ### end Alembic commands ###
