"""hz chto

Revision ID: 4b850abf0d16
Revises: af7e8afec600
Create Date: 2023-05-04 22:16:15.174141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b850abf0d16'
down_revision = 'af7e8afec600'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('parse_mode', sa.String(), nullable=False))
    op.add_column('prompts', sa.Column('welcome_message', sa.String(), nullable=True))
    op.add_column('prompts', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('fk_prompts_owner_users', 'prompts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_prompts_user_id_users'), 'prompts', 'users', ['user_id'], ['user_id'])
    op.drop_column('prompts', 'owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('owner', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_prompts_user_id_users'), 'prompts', type_='foreignkey')
    op.create_foreign_key('fk_prompts_owner_users', 'prompts', 'users', ['owner'], ['user_id'])
    op.drop_column('prompts', 'user_id')
    op.drop_column('prompts', 'welcome_message')
    op.drop_column('prompts', 'parse_mode')
    # ### end Alembic commands ###
